sync files from corpusops.bootstrap

diff --git a/lxc_create/templates/bin/cops_shell_common b/lxc_create/templates/bin/cops_shell_common
--- a/lxc_create/templates/bin/cops_shell_common
+++ b/lxc_create/templates/bin/cops_shell_common
@@ -9,6 +9,19 @@ ANSIBLE_FILTER_OUTPUT="${ANSIBLE_FILTER_OUTPUT}))"
 DEFAULT_COPS_URL="https://github.com/corpusops/corpusops.bootstrap.git"
 
 # BEGIN: corpusops common glue
+readlinkf() {
+    if ( uname | egrep -iq "linux|darwin|bsd" );then
+        if ( which greadlink 2>&1 >/dev/null );then
+            greadlink -f "$@"
+        elif ( which perl 2>&1 >/dev/null );then
+            perl -MCwd -le 'print Cwd::abs_path shift' "$@"
+        elif ( which python 2>&1 >/dev/null );then
+            python -c 'import os,sys;print(os.path.realpath(sys.argv[1]))' "$@"
+        fi
+    else
+        readlink -f "$@"
+    fi
+}
 # scripts vars
 SCRIPT=$0
 LOGGER_NAME=${LOGGER_NAME-$(basename $0)}
@@ -28,12 +41,14 @@ SYSTEM_COPS_ROOT=${SYSTEM_COPS_ROOT-$DEFAULT_COPS_ROOT}
 DOCKER_COPS_ROOT=${DOCKER_COPS_ROOT-$SYSTEM_COPS_ROOT}
 COPS_URL=${COPS_URL-$DEFAULT_COPS_URL}
 BASE_PREPROVISION_IMAGES="ubuntu:latest_preprovision"
+BASE_PREPROVISION_IMAGES="$BASE_PREPROVISION_IMAGES corpusops/ubuntu:18.04_preprovision"
 BASE_PREPROVISION_IMAGES="$BASE_PREPROVISION_IMAGES corpusops/ubuntu:16.04_preprovision"
 BASE_PREPROVISION_IMAGES="$BASE_PREPROVISION_IMAGES corpusops/ubuntu:14.04_preprovision"
 BASE_PREPROVISION_IMAGES="$BASE_PREPROVISION_IMAGES corpusops/centos:7_preprovision"
 BASE_CORE_IMAGES="$BASE_CORE_IMAGES corpusops/ubuntu:latest"
 
 BASE_CORE_IMAGES="$BASE_CORE_IMAGES corpusops/ubuntu:latest"
+BASE_CORE_IMAGES="$BASE_CORE_IMAGES corpusops/ubuntu:18.04"
 BASE_CORE_IMAGES="$BASE_CORE_IMAGES corpusops/ubuntu:16.04"
 BASE_CORE_IMAGES="$BASE_CORE_IMAGES corpusops/ubuntu:14.04"
 BASE_CORE_IMAGES="$BASE_CORE_IMAGES corpusops/centos:7"
@@ -444,6 +459,87 @@ get_python2() {
     done
     echo $py2
 }
+has_python_module() {
+    local py="${py:-python}"
+    for i in $@;do
+        if ! ( "${py}" -c "import $i" 2>/dev/null );then
+            return 1
+        fi
+     done
+}
+pymod_ver() {
+    local mod="${1}"
+    local py="${2:-${py:-python}}"
+    "$py" -c "from __future__ import print_function;import $mod;print($mod.__version__)"
+}
+install_pip() {
+    local py="${1:-python}"
+    local DEFAULT_PIP_URL="https://bootstrap.pypa.io/get-pip.py"
+    local PIP_URL="${PIP_URL:-$DEFAULT_PIP_URL}"
+    PIP_INST="$(mktemp)"
+    log "Reinstalling pip via $PIP_URL (copy to $PIP_INST)"
+    if ! ( "$py" -c "import urllib; print urllib.urlopen('$PIP_URL').read()" > "$PIP_INST" );then
+        log "Error downloading pip installer"
+        return 1
+    fi
+    $(may_sudo) "$py" "$PIP_INST" -U pip setuptools six
+}
+uninstall_at_least_pymodule() {
+    local py="${3:-${py-python}}"
+    local ver="${2}"
+    local mod="${1}"
+    local import="${4:-${1}}"
+    if ( ( has_python_module "$mod" ) && ( version_lt "$(pymod_ver "$mod" "$py")" "$ver" ) );then
+        local modd=$($py -c "from __future__ import print_function;import $import,os;print(os.path.dirname($import.__file__.replace('/__init__.pyc', '')))")
+        local modb="$HOME/.$mod.backup.$chrono.tar.bz2"
+        ( log "Backup mod install in $modb" \
+          && if [ -e "$modd/${import}.py" ];then
+            tar cjf "$modb" $modd/${import}.py* $modd/${mod}*egg-info &&\
+                $(may_sudo) rm -rf $modd/${import}.py* $modd/${mod}*egg-info; \
+            elif [ -e "$modd/${import}" ];then
+                tar cjf "$modb" $modd/${import} $modd/${mod}*egg-info &&\
+                    $(may_sudo) rm -rf $modd/${import} $modd/${mod}*egg-info; \
+            fi && log "Upgrading now from legacy pre $mod $ver" ) || \
+        die_in_error "Removing legacy $mod failed"
+    fi
+}
+upgrade_pip() {
+    local py="${1:-python}"
+    local pyc="$(get_command "$py")"
+    local dpy="$(dirname $pyc)"
+    local chrono=$(date +%F_%T|sed -e "s/:/-/g")
+    # force reinstalling pip in same place where it is (not /usr/local but /usr)
+    # __version__ is set by pip, uninstall last
+    if ( version_lt "$($py -V 2>&1|awk '{print $2}')" "3.0" );then
+        vv uninstall_at_least_pymodule requests  2.18.3 "$py"
+        vv uninstall_at_least_pymodule pyasn1    0.4.2  "$py"
+        vv uninstall_at_least_pymodule urllib3   1.20   "$py"
+        vv uninstall_at_least_pymodule pyopenssl 18.0.0 "$py" OpenSSL
+    fi
+    uninstall_at_least_pymodule six     1.11.0
+    uninstall_at_least_pymodule chardet 2.3.0
+    uninstall_at_least_pymodule pip     2.0
+    if ! ( has_python_module pip );then
+        install_pip "$py" || die "pip install failed for $py"
+        if ! ( has_python_module pip );then
+            log "pip not found for $py"
+            return 1
+        fi
+    fi
+    log "ReInstalling pip for $py"
+    if ( corpusops_use_venv );then
+        local maysudo=""
+    else
+        local maysudo=$(may_sudo)
+    fi
+    vv $maysudo "${py}" -m pip install -U setuptools \
+        && vv $maysudo "${py}" -m pip install -U pip six urllib3\
+        && vv $maysudo "${py}" -m pip install chardet \
+        && if ( version_lt "$($py -V 2>&1|awk '{print $2}')" "3.0" );then
+            vv $maysudo "${py}" -m pip install -U backports.ssl_match_hostname ndg-httpsclient pyasn1 &&\
+            vv $maysudo "${py}" -m pip install urllib3 pyopenssl
+        fi
+}
 make_virtualenv() {
     local py=${1:-$(get_python2)}
     local DEFAULT_VENV_PATH=$SCRIPT_ROOT/venv
@@ -483,31 +579,34 @@ make_virtualenv() {
         --system-site-packages --unzip-setuptools \
         "${venv_path}" &&\
     ( . "${venv_path}/bin/activate" &&\
-      "${venv_path}/bin/easy_install" -U setuptools &&\
-      "${venv_path}/bin/pip" install -U pip &&\
+      upgrade_pip "${venv_path}/bin/python" &&\
       deactivate; )
     fi
 }
 ensure_last_python_requirement() {
-    local PIP=${PIP:-pip}
     local COPS_PYTHON=${COPS_PYTHON:-python}
-    local i=
+    local COPS_UPGRADE=${COPS_UPGRADRE:-"-U"}
     local PIP_CACHE=${PIP_CACHE:-${VENV_PATH:-$(pwd)}/cache}
     # inside the for loop as at first pip can not have the opts
     # but can be upgraded to have them after
     local copt=
-    if "$py" "$PIP" --help | grep -q download-cache; then
+    if "$py" -m pip --help | grep -q download-cache; then
         copt="--download-cache"
-    elif $PIP --help | grep -q cache-dir; then
+    elif "$py" -m pip --help | grep -q cache-dir; then
         copt="--cache-dir"
     fi
     log "Installing last version of $@"
-    if [[ -n "$copt" ]];then
-        vvv "$COPS_PYTHON" "$PIP" install \
-            --src "$(get_eggs_src_dir)" -U $copt "${PIP_CACHE}" $@
+    if ( corpusops_use_venv );then
+        local maysudo=""
     else
-        vvv "$COPS_PYTHON" "$PIP" install \
-            --src "$(get_eggs_src_dir)" -U $@
+        local maysudo=$(may_sudo)
+    fi
+    if [[ -n "$copt" ]];then
+        vvv $maysudo "$COPS_PYTHON" -m pip install \
+            --src "$(get_eggs_src_dir)" $COPS_UPGRADE $copt "${PIP_CACHE}" $@
+    else
+        vvv $maysudo "$COPS_PYTHON" -m pip install \
+            --src "$(get_eggs_src_dir)" $COPS_UPGRADE $@
     fi
 }
 usage() { die 128 "No usage found"; }
